### ISSUE TITLE
FixMessageEncoder timestamp question

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#181]
https://github.com/real-logic/artio/blob/907a47012f4e496998f6957e1b3c72868707fd2c/artio-core/src/main/java/uk/co/real_logic/artio/protocol/GatewayPublication.java#L129

FixMessageEncoder timestamp is using nanosecond,
If use default SystemNanoClock, then it seems impossible for user to filter the log by timestamp.

And below method parameter name is wrong, should be xxxInNs.

https://github.com/real-logic/artio/blob/907a47012f4e496998f6957e1b3c72868707fd2c/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/FixMessagePredicates.java#L75

**Comment by RichardWarburton** [comment]
It looks like method parameter names are wrong - I'll push a fix now. I'm not sure what else is a problem though - I think if you put the parameter values on that query in nanoseconds then you'll get the messages filtered.

**Comment by guoguanglei** [comment]
What i mean is Java [System.nanoTime()](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--) is used for measure elapsed time, it should not used for absolute timestamp.
So if user want to filter the log by timestamps, they need to provide their own nanoTime implementation.

**Comment by RichardWarburton** [comment]
Hi Gary,

Yeah, the original motivation for providing a timestamp value was actually for measuring performance timings - which is why it uses nanoTime(). You can provide your own nanoTime() implementation through the `CommonConfiguration.nanoClock(NanoClock)` method if you have something more precise available to your system.

I'm reticent to add two timestamps to every message we send through the system. Maybe it would be best to change the clock name in order to remove reference to the precision of the clock (Nanoseconds vs Milliseconds) that way users can just store whatever precision is most appropriate for them. If they're recording timing data they can use `System.nanoTime()`, if they've got a stable timestamp value that provides nanoseconds they can use that, if they've not got anything special but want to `System.currentTimeMillis()` they can also use that. Would that help resolve the issue?

**Comment by guoguanglei** [comment]
Sounds good. Thank you Richard.
