### ISSUE TITLE
Sequence numbers only get persisted on shutdown

### ISSUE THREAD

**Issue by mprusakov-rbc** [real-logic/artio#231]
Even though Artio fix client uses memory mapped files to store sequence numbers, these seem to be updated only on graceful shutdown. This generally works but is a problem if the application gets killed - in this case upon start up Artio would be requesting all messages from the beginning of old session even though these have already been processed.

Artio does support custom ways of supplying sequence numbers, which is great however it would be beneficial to understand why sequence numbers do not get persisted during runtime via memory mapped files, like say performance counters. Thus could you please clarify?

**Comment by RichardWarburton** [comment]
Thanks for your question. Currently we flush the sequence number index to disk periodically, when it spots an Aeron termbuffer roll. So when at max the number of bytes in a term buffer pass through the system. So it's not only when closed, but it certainly won't happen all the time.

We don't flush it to disk everytime we update the file in order to avoid writing excessive data to disk. That index is also checksummed and potentially has updates in different places, so you can't assume that an update of a single value will be atomically persisted. What we do at the moment is keep two memory mapped files - one that's update-able and one that is atomically consistent on disk and flip them periodically. The filesystem rename operation is atomic so if Artio gets killed then the on disk copy should always be correct.

Performance Counters are a different case. The updates there are usually just updating a long, so it doesn't matter. Plus the performance counter file isn't checksummed, so if your disk does get corrupted its possible that those numbers will be wrong, but they're just performance counters so its not critical.

If you've got a suggestion for ensuring that the writers are persisted in a more up to date way, that also doesn't increase disk i/o, ensures writes are atomic and also gives us the ability to check the integrity of the file then I'd be interested in hearing a proposal. I'm not super-enthusiastic about the current design.
