### ISSUE TITLE
Unable to purge archive

### ISSUE THREAD

**Issue by mprusakov-rbc** [real-logic/artio#240]
Upon startup it takes a long time to index messages in the archive. Most of them are irrelevant as only recent messages have any value and old ones can be discarded safely. Simply deleting the files in the archive doesn't work as their position is referenced by the replay-positions file.

Do I understand correctly that in order to reduce the archive the application needs to
1) read the positions in replay-positions file
2) use catalog to work out whether messages are still relevant
3) remove the irrelevant positions from the file
4) remove the files from the archive

Thanks.

**Comment by RichardWarburton** [comment]
Thanks for raising this issue. My expected usage is that people periodically just rotate their log data and archive it. For example at an end of the day event. Is this not possible in your case?

I've had a bit of a think and I'm wondering why it takes so long to index messages on startup. The way Artio is designed the indexer agent should be keeping up with the progress of the Framer agent. The scan on startup should just be of files that we are behind with. So that indicates to me that either:

1) Your Archiver is behind your Framer. You should be able to see from the Aeron counters what the position of the Archiver subscription is, or from the contents of the position indexes. Is this the case?
2) Our logic for scanning these logs on startup is suboptimal and we're scanning more data that we need to.

**Comment by mprusakov-rbc** [comment]
Just to make sure I understand this: we can only rotate the log data when we reset the sequence numbers (i.e. beginning of the week)? Otherwise with both replay-index and replay-positions gone we would not be able to replay any fix messages, right?

I also got to the bottom of my long start ups. For some reason when i was looking at the code i got an impression that Artio re-indexes each time, which is my mistake. After your comments i went through the logs and noticed an interesting thing:

1550845136049:main[INDEX] : Catchup [ReplayIndex]: recordingId = 1, recordingStopped @ 57920, indexStopped @ 50496
...
1550845136284:main[INDEX] : Catchup [ReplayIndex]: recordingId = 9, recordingStopped @ 21783072, indexStopped @ 21783008
**1550845136364:main[INDEX] : Catchup [ReplayIndex]: recordingId = 13, recordingStopped @ 6245024, indexStopped @ 4096**
1550845141146:main[INDEX] : Catchup [ReplayIndex]: recordingId = 17, recordingStopped @ 17888,
... 
1550845144585:main[INDEX] : Catchup [ReplayIndex]: recordingId = 11, recordingStopped @ 8113024, indexStopped @ 8112960
**1550845145018:main[INDEX] : Catchup [ReplayIndex]: recordingId = 15, recordingStopped @ 6256096, indexStopped @ 6496**
1550845149839:main[INDEX] : Catchup [ReplayIndex]: recordingId = 19, recordingStopped @ 23808, indexStopped @ 22016

Most recordings are almost at the end and just 13 and 15 are way off. I replayed those manually and apparently these only have hearbeats (TEMPLATE_ID == 16). My guess is that at some point we got disconnected from the venue but both library and engine were running. Problem is that ReplayIndex seems to be dropping everything but fix messages (https://github.com/real-logic/artio/blob/master/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/ReplayIndex.java:128) So I was wondering whether it should update position in case of a heartbeat?

Many many thanks in advance.

**Comment by RichardWarburton** [comment]
Hi,

Yes - you're right that's exactly what should happen. Thanks for the debug
information.

**Comment by RichardWarburton** [comment]
Closing this issue since the `resetState()` operation solves this requirement I think.
