### ISSUE TITLE
TestRequest out of sequence should immediately trigger ResendRequest

### ISSUE THREAD

**Issue by epickrram** [real-logic/artio#312]
When a client sends a TestRequest with a too-high sequence number, Artio responds with a Heartbeat, then a ResendRequest. I would expect that the ResendRequest should come first.

I can't find a definitive answer to what the expected behaviour should be, but certain sources[1] imply that the TestRequest should be ignored until resent.

PR containing failing test:
https://github.com/real-logic/artio/pull/311

1) https://fixwiki.org/fixwiki/ResendRequest
"if message number 7 is missed and 8-9 received, the application should ignore 8 and 9 and ask for a resend of 7-9"

**Comment by RichardWarburton** [comment]
Thanks for the bug report and test case Mark.

The thing is that in the case of the test request it probably won't be resent, since administrative messages are gap-filled. To quote the FIX Spec (Volume 2, "Message Recovery" Section) - "The administrative messages which are not to be resent are: Logon, Logout, ResendRequest, Heartbeat, TestRequest and SeqReset-Reset and SeqReset-GapFill." So if you don't respond to a test request at this juncture then you probably won't get it again.

I'm still trying to get a handle on whether the current behaviour is right but I wanted to clarify this gapfilling of admin messages behaviour.

**Comment by RichardWarburton** [comment]
I think it's also worth clarifying that in not all situations do you want to ignore the message that's too high. If it's a logon message that's too high (the most common case IME) then you're supposed to reply with a message to acknowledge the logon, and then resend request (eg: quickfix acceptance test 1a_ValidLogonMsgSeqNumTooHigh.def)

**Comment by RichardWarburton** [comment]
I've pushed a fix for this issue as I think intuitively you're right - but it's not 100% clear from my reading of the FIX spec that this is the case and it doesn't seem to have an associated quickfix acceptance test.

**Comment by epickrram** [comment]
I agree that as a client I would gapfill, rather than resend the TestRequest, but it was more the unexpected Heartbeat. The reason I found the issue was because of this QF/J test case:

https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-core/src/test/resources/quickfix/test/acceptance/definitions/server/fix44/RejectResentMessage.def

which fails because it gets a HB before the ResendRequest.
