### ISSUE TITLE
Don't revert ownership of offline sessions to the Engine in Sole Library mode

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/artio#361]

**Comment by guoguanglei** [comment]
One issue with this is we can not try to re-connect the session with that FixLibrary when Artio work as initiator.

If try to re-connect, we will receive "Duplicate Session..." because isOwnedSession in below code return true.

https://github.com/real-logic/artio/blob/d9407871676d5235f8fd323ca68c62e188b3ce5b/artio-core/src/main/java/uk/co/real_logic/artio/engine/framer/Framer.java#L854

Can we make the retain owner ship configurable and default to false?

**Comment by RichardWarburton** [comment]
Hi Gary,

Adding more and more configuration options for different behaviors is a bit of a whack-a-mole situation. I think setting InitialAcceptedSessionOwner to SOLE_LIBRARY affecting initiating sessions is a bug. That shouldn't be the case. If a library reconnects the session and owns it then Artio should just make that work without further configuration. Happy to fix that.

Am I right in thinking that this can just be replicated by having an initiator Session connect and then disconnect and then attempt to reconnect?

**Comment by guoguanglei** [comment]
> Am I right in thinking that this can just be replicated by having an initiator Session connect and then disconnect and then attempt to reconnect?

Correct

**Comment by RichardWarburton** [comment]
@guoguanglei I've pushed a fix for this. It will be in the next Artio release - hopefully today.
