### ISSUE TITLE
Fix Logging agent does not log logon message if session fails to authenticate.

### ISSUE THREAD

**Issue by AmitA396** [real-logic/artio#402]
We are using the FixLoggingAgent as shown in wiki and it seems that the incoming logon request is not logged in case of session fails to authenticate.
Also it seems no response is sent back to sender about authentication failure.

We are able to see application log about authentication but we don't find the corresponding 35=A message or 35=A or 5 as response in logs.

**Comment by RichardWarburton** [comment]
Hi Amit,

So there's a few things here. Firstly I'm assuming by FixLoggingAgent you mean the `-Dfix.core.debug=FIX_MESSAGE` configuration option. If not please let me know.

(1) I've just pushed a fix here (f99327898) so that messages that fail authentication get logged under the `FIX_MESSAGE` LogTag. They will be prefixed with "Auth Reject".
(2) On an existing system if you want to read exactly what Artio received from TCP then you can also use the FIX_MESSAGE_TCP logtag. I wouldn't necessarily recommend enabling this by default - because its before FIX messages get parsed, so if the client sends you two FIX Messages that are read in a single TCP read syscall then they will appear as one. But it can be useful if you're trying to diagnose exactly what happened in weird scenarios.
(3) Re "Also it seems no response is sent back to sender about authentication failure." - this is how auth failures are supposed to be handled in FIX. If you want to send back a message to your users in the case of an authentication failure then you can use the `reject(Encoder, long)` method on the `AuthenticationProxy` argument passed to your `AuthenticationStrategy`. It's worth noting that choosing to send back messages in the case of an authentication failure has associated risks. If you reply to this message explaining whether the failure is a missing username or password then a malicious user could potentially "probe" your list of users by sending in different username/password strings. Any reply also increases the resources used on a server by a failed authentication attempt and thus increases the chance of DDOS. So the default prioritises security over friendliness.

I plan to do a release today with that additional log-line in. If I've misunderstood the way that you're logging then please let me know and I can investigate further.

**Comment by AmitA396** [comment]
@RichardWarburton 
I agree to the point of unauthorized access and I was not sure that it was done on purpose or not.
For logging, we are logging using inbound subscription and I was expecting 35=A to be logged in using that.
        inboundSubscription = aeron.addSubscription(libraryAeronChannel, inboundStreamId);

**Comment by RichardWarburton** [comment]
Yeah - I've had a chat with Shaun and he clarified the confusion, apologies. I've just pushed a change for that (65ddb89d7). It slightly changes the `FixMessageLogger` API - but that should help make it easier to understand the output.
