### ISSUE TITLE
Wrong version in Maven Repository Central - 0.94

### ISSUE THREAD

**Issue by vitor-tadashi** [real-logic/artio#428]
So I was searching for the new method  [tryUpdateLastReceivedSequenceNumber](https://github.com/real-logic/artio/compare/0.94...master#diff-052a55b6358354162f86f5ced058bd96332bf1211da06ac9d71741180818c12aR842) after updating the version and I couldn't find it.

To make sure I decompiled the jar that was coming from Maven Repository Central and was wrong.

Is it possible to fix _that?_

**Comment by RichardWarburton** [comment]
Hi Vitor,

Thanks for this bug report. I'm on holiday this week but will investigate
when I get back.

**Comment by RichardWarburton** [comment]
Hi @vitor-tadashi,

I've just investigated here and 0.94 was released before the switch over to `tryUpdateLastReceivedSequenceNumber` that you mentioned. 0.94 only contains `tryUpdateReceivedSequenceNumber`, which has been renamed and fixed in head. That will be in the next release of Artio.

regards,

  Richard
